[package]
name = "boost_bind"
description = "Boost C++ library boost_bind packaged using Zanbil"
version = "0.1.0"
edition = "2024"
links = "boost_bind"
license = "BSL-1.0"
repository = "https://github.com/zanbilify/boost_bind"

[package.metadata.zanbil]
make_dependencies_public = true

[dependencies]
boost_config = { version = "0.1.0", path = "../boost_config" }
boost_core = { version = "0.1.0", path = "../boost_core" }

[build-dependencies]
zanbil-boost-build = "0.1.0"
